### ISSUE TITLE
Did not find where to get Adyen token

### ISSUE THREAD

**Issue by trungp** [Adyen/adyen-checkout-ios#11]
Hello,

Could you please help me where I can get the Adyen token for the sdk?. I see it's required to config token for library by this code:
`Checkout.shared.token = "YOUR_ADYEN_TOKEN"`

But I could not find where I can get the token.

Thanks,

**Comment by danipralea** [comment]
you need to either go to your dashboard or talk to their support team directly

**Comment by olutsenko** [comment]
Please let us know if you have any further questions. Closing issue.
