### ISSUE TITLE
hello 

### ISSUE THREAD

**Issue by mafeng-Bryant** [Adyen/adyen-checkout-ios#13]
is their Object-C Version  AdyenCheckout-ios ？

**Comment by olutsenko** [comment]
Hi mafeng-Bryant,

At the moment there is only Swift version of the framework. If you want to use it in your Obj-C project, you can Mix and Match Swift with Obj-C. 

More details about Mix and Match —  https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html#//apple_ref/doc/uid/TP40014216-CH10-ID122

Regards,
Oleg
