### ISSUE TITLE
Swift 3 / Xcode 8

### ISSUE THREAD

**Issue by georgij** [Adyen/adyen-checkout-ios#20]
After switching the Swift 3 I was not able to use Adyen Checkout.

**Comment by olutsenko** [comment]
Hi Georg,

At the moment we support Swift 2.3 if you want to use iOS 10 SDK on Xcode 8.

Swift 3 support is coming later in the next release.

Regards,
Oleg

**Comment by fnazarios** [comment]
Waiting Swift 3 compatible version!

**Comment by mortenbekditlevsen** [comment]
Ditto here. Currently holding us back from adding Adyen Checkout as a payment option.

**Comment by fnazarios** [comment]
Hi.

I did open a pull request compiling on Xcode 8 and Swift 3.
https://github.com/Adyen/adyen-checkout-ios/pull/21

**Comment by olutsenko** [comment]
Hi @fnazarios 

Thanks a lot for your contribution, it's merged.

Guys, you can go ahead and update your pods to get Swift 3 support.

Regards,
Oleg
