### ISSUE TITLE
Problem obtaining SecKeyRef

### ISSUE THREAD

**Issue by vash15** [Adyen/adyen-checkout-ios#23]
Hi, when I try the example on iPhone 7 Simulator and iOS 10.0 obtain this error:

> Problem obtaining SecKeyRef

But, on iPhone 6 Simulator and iOS 8.4 it's ok.
Any ideas?
Thanks

**Comment by olutsenko** [comment]
Hi @vash15 

We also see this issue happening on simulator with Xcode 8. Our advise is to use iOS device before Apple provides a fix.

Regards,
Oleg
