### ISSUE TITLE
Gift Card

### ISSUE THREAD

**Issue by stephenkeep** [Adyen/adyen-checkout-ios#3]
Hi,

Firstly thanks for making this project. I am looking to integrate with Adyen for a client of ours and they have the option to pay with a gift card on their website (powered by Adyen).

Is this functionality provided by this SDK?

Does this SDK support paying by Apple Pay?

Thanks

Steve

**Comment by xslim** [comment]
Hello Stephen! We are working into implementing alternative payment methods in very near feature. Let me know privately about alternatives you would like to have and we can do some beta-testing with you.

**Comment by olutsenko** [comment]
Please let us know if you have any further questions. Closing now.
