### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by brossdu** [Adyen/adyen-checkout-ios#9]
CheckoutPayment(request: self.request, encryptedData: paymentData) don't compile when we use pod. 
Error message : 
    'CheckoutPayment' cannot be constructed because it has no accessible initializers

**Comment by brossdu** [comment]
I just Checkout the last version with :
pod 'AdyenCheckout', :git => 'https://github.com/Adyen/AdyenCheckout-ios'

And it works now

**Comment by readefries** [comment]
Ergo, could you please update the version in cocoapods?

**Comment by olutsenko** [comment]
Released new pod version with Xcode 8 / swift 2.3 support. Closing issue.
